apiVersion: 1

datasources:
  - name: Prometheus
    uid: prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Postgres
    uid: pg
    type: grafana-postgresql-datasource
    access: proxy
    url: tsdatabase:5432
    user: $DB_USER
    jsonData:
      database: $DB_NAME
      sslmode: disable
    secureJsonData:
      password: $DB_PASSWORD